# Generated by Django 4.2.5 on 2023-11-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_option',
            field=models.CharField(choices=[('pending', 'pending'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('returned', 'returned'), ('Rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
