# Generated by Django 4.2.5 on 2023-11-11 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_orderitem_payment_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CroppedImage',
        ),
        migrations.AddField(
            model_name='refferalcode',
            name='discountprice',
            field=models.IntegerField(default=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
